### ISSUE TITLE
submit_selected and the interface should do something reasonable when no files are selected

### ISSUE THREAD

**Issue by steven-wolfman** [eagubsi/JupyterCanvasSubmit#1]
Right now, there's no special handling for submission of an empty set of files. I suspect we want something special to happen, probably in submit_selected. I cannot currently test since I have no student token!

**Comment by eagubsi** [comment]
So it just produces an error, we can handle it and produce a more readable error message. 

![submit no files error](https://user-images.githubusercontent.com/17133840/71804632-eeaec180-3018-11ea-9962-14126292d79b.JPG)

**Comment by steven-wolfman** [comment]
Sure; a clearer error would be good, but I was also thinking we could deal with this earlier in the process. E.g., when you click Submit, it could immediately come back with "No file has been selected to submit. Please select one or more files and try again."

Related: can we auto-select the current file? (And should we in response to this error. E.g., do so and then "No file was selected to submit. In case you intended to select the current file, it appears to be FILE_NAME_HERE. That file has been selected, and you can submit it by pressing the Submit button again."

**Comment by eagubsi** [comment]
Autoselects first file in the list of files so this shouldn't be an issue anymore.

**Comment by eagubsi** [comment]
Also, helpfully fails when no files are selected
